version: '3.9'

volumes:
  fastapi-basic-local-postgres: {}

services:
  fastapi-basic:
    container_name: fastapi-basic
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: /start-sh

  postgres:
    build:
      context: .
      dockerfile: docker-compose-local/Dockerfile
    image: fastapi-basic-local-postgres
    container_name: fastapi-basic-local-postgres
    volumes:
      - fastapi-basic-local-postgres:/var/lib/postgresql/data:Z
    env_file:
      - .env
    ports:
      - "6432:5432"
