version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=fastapi-basic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=090816
  fastapi_basic:
    container_name: fastapi_basic
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - db
